services:
  postgres:
    image: postgres:16
    container_name: oc_postgres
    environment:
      POSTGRES_USER: oc
      POSTGRES_PASSWORD: ocpass
      POSTGRES_DB: oc_db
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: oc_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: oc
      RABBITMQ_DEFAULT_PASS: ocpass
